# Generated by Django 4.2.5 on 2023-09-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file',
            field=models.CharField(default='hello', max_length=10000),
            preserve_default=False,
        ),
    ]
