# Generated by Django 4.2.5 on 2023-09-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_alter_fileupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.BinaryField(),
        ),
    ]
