# Generated by Django 4.2.4 on 2023-08-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedProject',
            fields=[
                ('baseproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_project.baseproject')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_projects', to='rejectedProject.rejectedreason')),
            ],
            bases=('base_project.baseproject',),
        ),
    ]
