# Generated by Django 4.2.4 on 2023-09-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
