# Generated by Django 4.2.4 on 2023-09-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingdocinvoice_accountingdocpriceproposal_and_more'),
        ('base_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproject',
            name='client',
        ),
        migrations.RemoveField(
            model_name='baseproject',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='baseproject',
            name='total',
        ),
        migrations.AddField(
            model_name='baseproject',
            name='root_price_proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_project', to='accounting.accountingdocpriceproposal'),
        ),
    ]
