# Generated by Django 4.2.4 on 2023-09-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_project', '0003_baseproject_client_baseproject_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproject',
            name='comments',
        ),
        migrations.AddField(
            model_name='baseproject',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
