# Generated by Django 4.2.4 on 2023-09-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_project', '0004_remove_baseproject_comments_baseproject_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproject',
            name='last_comment',
        ),
    ]
