# Generated by Django 4.2.5 on 2023-09-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0005_alter_fileupload_file'),
        ('base_project', '0006_remove_baseproject_client_remove_baseproject_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproject',
            name='files',
            field=models.ManyToManyField(to='file_upload.fileupload'),
        ),
    ]
