# Generated by Django 4.2.4 on 2023-08-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('taxId', models.CharField(blank=True, max_length=100)),
                ('paymentTerms', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('emails', models.JSONField(default=list)),
                ('morning_id', models.CharField(blank=True, max_length=100)),
                ('morning_last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
