# Generated by Django 4.2.4 on 2023-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='api_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
