# Generated by Django 4.2.4 on 2023-09-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_api_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='morning_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
