# Generated by Django 4.2.4 on 2023-08-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwaitingProject',
            fields=[
                ('baseproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_project.baseproject')),
                ('alert_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('base_project.baseproject',),
        ),
    ]
