# Generated by Django 4.2.4 on 2023-09-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDocInvoice',
            fields=[
                ('accountingdoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.accountingdoc')),
            ],
            bases=('accounting.accountingdoc',),
        ),
        migrations.CreateModel(
            name='AccountingDocPriceProposal',
            fields=[
                ('accountingdoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.accountingdoc')),
            ],
            bases=('accounting.accountingdoc',),
        ),
        migrations.CreateModel(
            name='AccountingDocReceipt',
            fields=[
                ('accountingdoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.accountingdoc')),
            ],
            bases=('accounting.accountingdoc',),
        ),
        migrations.AddField(
            model_name='accountingdoc',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountingdoc',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
        migrations.AddField(
            model_name='accountingdoc',
            name='doc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountingdoc',
            name='base_price_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs', to='accounting.accountingdocpriceproposal'),
        ),
    ]
