# Generated by Django 4.2.4 on 2023-09-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingdocinvoice_accountingdocpriceproposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdoc',
            name='based_on',
            field=models.ManyToManyField(blank=True, related_name='based_docs', to='accounting.accountingdoc'),
        ),
    ]
