# Generated by Django 4.2.4 on 2023-09-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountingdoc_based_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingdoc',
            name='updated_at',
        ),
    ]
