# Generated by Django 4.2.4 on 2023-09-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_project', '0003_baseproject_client_baseproject_total'),
        ('accounting', '0004_remove_accountingdoc_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingdoc',
            name='based_on',
        ),
        migrations.AddField(
            model_name='accountingdoc',
            name='childs',
            field=models.ManyToManyField(blank=True, related_name='parent_docs', to='accounting.accountingdoc'),
        ),
        migrations.AddField(
            model_name='accountingdoc',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_project.baseproject'),
        ),
        migrations.AlterField(
            model_name='accountingdoc',
            name='base_price_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.accountingdocpriceproposal'),
        ),
        migrations.AlterField(
            model_name='accountingdoc',
            name='morning_id',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
