# Generated by Django 4.2.4 on 2023-09-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_accountingdoc_based_on_accountingdoc_childs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingdoc',
            name='base_price_proposal',
        ),
        migrations.RemoveField(
            model_name='accountingdoc',
            name='project',
        ),
        migrations.AddField(
            model_name='accountingdoc',
            name='root_price_proposals',
            field=models.ManyToManyField(blank=True, related_name='child_docs', to='accounting.accountingdocpriceproposal'),
        ),
    ]
