# Generated by Django 4.2.4 on 2023-09-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_accountingdoc_childs_accountingdocrelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingdoc',
            name='based_on',
        ),
    ]
