# Generated by Django 4.2.4 on 2023-10-02 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_remove_accountingdoc_based_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDocCancelInvoice',
            fields=[
                ('accountingdoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.accountingdoc')),
            ],
            bases=('accounting.accountingdoc',),
        ),
    ]
